use chorus::block::block_id;
use chorus::registry::block_registry::BlockRegistry;

#[derive(Debug)]
pub struct BlockIds {
    pub air: i32,
    pub stone: i32,
    pub water: i32,
    pub water_flowing: i32,
    pub ice: i32,
    pub bedrock: i32,
    pub grass: i32,
    pub dirt: i32,
    pub sand: i32,
    pub sandstone: i32,
    pub gravel: i32,
    pub lava: i32,
    pub lava_still: i32,
    pub clay: i32,
    pub cobblestone: i32,
    pub mossy_cobblestone: i32,
    pub chest: i32,
    pub mob_spawner: i32,
    pub coal_ore: i32,
    pub iron_ore: i32,
    pub gold_ore: i32,
    pub redstone_ore: i32,
    pub diamond_ore: i32,
    pub lapis_ore: i32,
    pub oak_log: i32,
    pub oak_leaves: i32,
    pub birch_log: i32,
    pub birch_leaves: i32,
    pub spruce_log: i32,
    pub spruce_leaves: i32,
    pub dandelion: i32,
    pub poppy: i32,
    pub tall_grass: i32,
    pub fern: i32,
    pub deadbush: i32,
    pub red_mushroom: i32,
    pub brown_mushroom: i32,
    pub reeds: i32,
    pub pumpkin: i32,
    pub cactus: i32,
    pub snow_layer: i32,
}

impl BlockIds {
    pub fn resolve(registry: &BlockRegistry) -> Self {
        let id = |identifier: &str| registry.get_block_id(identifier).unwrap_or(0);
        Self {
            air: id(block_id::AIR),
            stone: id(block_id::STONE),
            water: id(block_id::WATER),
            water_flowing: id(block_id::FLOWING_WATER),
            ice: id(block_id::ICE),
            bedrock: id(block_id::BEDROCK),
            grass: id(block_id::GRASS_BLOCK),
            dirt: id(block_id::DIRT),
            sand: id(block_id::SAND),
            sandstone: id(block_id::SANDSTONE),
            gravel: id(block_id::GRAVEL),
            lava: id(block_id::FLOWING_LAVA),
            lava_still: id(block_id::LAVA),
            clay: id(block_id::CLAY),
            cobblestone: id(block_id::COBBLESTONE),
            mossy_cobblestone: id(block_id::MOSSY_COBBLESTONE),
            chest: id(block_id::CHEST),
            mob_spawner: id(block_id::MOB_SPAWNER),
            coal_ore: id(block_id::COAL_ORE),
            iron_ore: id(block_id::IRON_ORE),
            gold_ore: id(block_id::GOLD_ORE),
            redstone_ore: id(block_id::REDSTONE_ORE),
            diamond_ore: id(block_id::DIAMOND_ORE),
            lapis_ore: id(block_id::LAPIS_ORE),
            oak_log: id(block_id::OAK_LOG),
            oak_leaves: id(block_id::OAK_LEAVES),
            birch_log: id(block_id::BIRCH_LOG),
            birch_leaves: id(block_id::BIRCH_LEAVES),
            spruce_log: id(block_id::SPRUCE_LOG),
            spruce_leaves: id(block_id::SPRUCE_LEAVES),
            dandelion: id(block_id::DANDELION),
            poppy: id(block_id::POPPY),
            tall_grass: id(block_id::TALL_GRASS),
            fern: id(block_id::FERN),
            deadbush: id(block_id::DEADBUSH),
            red_mushroom: id(block_id::RED_MUSHROOM),
            brown_mushroom: id(block_id::BROWN_MUSHROOM),
            reeds: id(block_id::REEDS),
            pumpkin: id(block_id::CARVED_PUMPKIN),
            cactus: id(block_id::CACTUS),
            snow_layer: id(block_id::SNOW_LAYER),
        }
    }
}
